#!/bin/bash -ex

. vm-functions

# register_channels channel1 channel2
register_channels rhel-7-server-rpms rhel-7-server-rhceph-1.3-osd-rpms rhel-7-server-rhceph-1.3-calamari-rpms rhel-7-server-rhceph-1.3-installer-rpms rhel-7-server-rhceph-1.3-osd-rpms rhel-7-server-rhceph-1.3-tools-rpms


# yum_install myrpm1 myrpm2
yum_install ceph-deploy system-config-firewall-base

# install ceph binaries on system ready for cluster
ceph-deploy install localhost


useradd ceph
passwd -d ceph
passwd -e ceph
echo 'ceph ALL=(ALL) NOPASSWD: ALL' >>/etc/sudoers

useradd demo
passwd -d demo
passwd -e demo
echo 'demo ALL=(ALL) NOPASSWD: ALL' >>/etc/sudoers

sed -i -e '/^#PermitEmptyPasswords/ a \
PermitEmptyPasswords yes' /etc/ssh/sshd_config

lokkit -p 22:tcp
lokkit -p 5900:tcp

# Configure ssh-key access for ceph nodes
mkdir -m 700 /home/ceph/.ssh
chown ceph:ceph /home/ceph/.ssh
cp id_rsa /home/ceph/.ssh/ && chown ceph:ceph /home/ceph/.ssh/id_rsa
cp id_rsa.pub /home/ceph/.ssh/ && chown ceph:ceph /home/ceph/.ssh/id_rsa.pub
cp authorized_keys /home/ceph/.ssh/ && chown ceph:ceph /home/ceph/.ssh/authorized_keys
chmod 644 /home/ceph/.ssh/authorized_keys
chmod 600 /home/ceph/.ssh/id_rsa
chmod 644 /home/ceph/.ssh/id_rsa.pub

# Create a copy of devices for storage pools
lvcreate -L10G -n storage-disk1 volgroup
lvcreate -L10G -n storage-disk2 volgroup
